---
- name: Test playbook to run 
  hosts: all
  user: ec2-user 
  become: true
  become_method: sudo
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts['kernel']






  # - name: Install telnet 
  #   ansible.builtin.yum:
  #     name:  telnet
  #     state: present    # absent  # latest # removed