---
- name: Test playbook to run 
  hosts: all
  user: ec2-user 
  become: true
  become_method: sudo
  tasks:
  
  - name: Install telnet 
    ansible.builtin.yum:
      name:  telnet
      state: present    # absent  # latest # removed